lo_platform_homepage:
    path:     /
    defaults: { _controller: LOPlatformBundle:Billet:index }


lo_platform_recapitulatif:
    path:     /recapitulatif
    defaults:
        _controller: LOPlatformBundle:Billet:recapitulatif
        id: 0



lo_platform_paiement:
    path:     /paiement
    defaults: { _controller: LOPlatformBundle:Billet:paiement, id: 0}