parameters:
    trancheAge: # prix exprimé en euros age + prix
        0: 0
        4: 8
        12: 16
        60: 12

    reducBillet: 10

    jourFerie:
        - "01/05"
        - "01/11"
        - "25/12"



services:
#    lo_platform.example:
#        class: LO\PlatformBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

    lo_platform.calculBillet:
        class: LO\PlatformBundle\Services\CalculBillet
        arguments: ["%trancheAge%", "%reducBillet%"]


    lo_platform.twig.extension.calculbillet:
        class: LO\PlatformBundle\Services\CalculBilletTwigExtension
        arguments:
            - "@lo_platform.calculBillet"
        tags:
            -  { name: twig.extension }



    lo_platform.validator.limiteBillet:
        class: LO\PlatformBundle\Validator\LimiteBilletsValidator
        arguments:
            - "@doctrine.orm.entity_manager"
        tags:
            - { name: validator.constraint_validator, alias: limiteBillet_validator}


    lo_platform.session.commande:
        class: LO\PlatformBundle\Services\SessionCommande
        arguments:
            - "@request_stack"


    lo_platform.validator.joursFermes:
        class: LO\PlatformBundle\Validator\JoursFermesValidator
        arguments:
            - "%jourFerie%"
        tags:
            - { name: validator.constraint_validator, alias: joursFeries_validator}

